---
- name: Sync Ubuntu machines
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    target_user: mbluteau
    target_group: mbluteau

  tasks:
  # Fish doesn't have a build for Ubuntu 24.04 Noble in its more 
  # up-to-date repo yet. Use the below once it does.
  #
  #- name: Add additional PPAs for installation sources
  #  ansible.builtin.apt_repository:
  #    repo: "{{ item }}"
  #    state: present
  #  loop:
  #    - ppa:fish-shell/release-3
  #
  #- name: Install specific version of fish and prevent upgrades
  #  ansible.builtin.apt:
  #    name: fish
  #    state: fixed
  #    version: '3.7.1-1'

  - name: Install apt-based packages
    ansible.builtin.apt:
      state: present
      pkg:
        - git
        - vim-gtk3
        - make
        - curl
        - inkscape
        - calibre
        - gnome-tweaks
        - evolution-ews
        - ssh
        - pandoc
        - texlive
        - btop
        - python-is-python3
        - pipx
        - restic
        - rclone
        - chrome-gnome-shell # for GNOME extensions
        - terminator # should also set the default terminal app
        - fish=3.7.*
        - pdftk-java
        - fzf
        - bat
        - fd-find
        # for AppImages and JetBrains Toolbox
        - libfuse2 
        - libxi6
        - libxrender1
        - libxtst6
        - mesa-utils
        - libfontconfig
        - libgtk-3-bin
        - tar
        - dbus-user-session
        # For connecting to android devices
        - android-sdk-platform-tools-common

  - name: Clean up
    ansible.builtin.apt:
      autoclean: yes
      autoremove: yes

  - name: Set default shell
    ansible.builtin.user:
      name: "{{ target_user }}"
      shell: /usr/bin/fish

  - name: Ensure vim temp directories exist
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ target_user }}"
      group: "{{ target_group }}"
    loop:
      - ~/.tmp
      - ~/.bkp
    become: false

  - name: Install vim plugins
    ansible.builtin.shell: |
      vim +PluginInstall +qall
    become: false
    become_user: "{{ target_user }}"

  - name: Check if fisher is in fish environment already
    ansible.builtin.shell:
      cmd: fish --command="fisher --version"
    register: is_fisher_installed
    become_user: "{{ target_user }}"
    ignore_errors: true
    
  - name: Install fisher plugin manager for fish
    # This is failing because the shell isn't fish. Need to find a way around
    # that.
    ansible.builtin.shell: |
      curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher && fisher update
    become_user: "{{ target_user }}"
    when: is_fisher_installed is failed
  
  - name: Install rust and cargo
    ansible.builtin.shell:
      cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      creates: ~/.cargo
    become_user: "{{ target_user }}"

  - name: Keyboard shortcuts and setup
    ansible.builtin.shell: |
      gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:swapcaps']"
      gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Primary><Alt>t', '<Primary><Alt>n']" 
      gsettings set org.gnome.settings-daemon.plugins.media-keys calculator "['<Control><Alt>k']" 
      gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Control><Alt>o']" 
      gsettings set org.gnome.settings-daemon.plugins.media-keys control-center "['<Control><Alt>m']" 
    become_user: "{{ target_user }}"

  - name: Install appimaged
    ansible.builtin.shell:
      cmd: fish appimaged.fish
      creates: ~/Applications/appimaged*.AppImage
    become_user: "{{ target_user }}"

  - name: Install vscode
    ansible.builtin.shell:
      cmd: fish vscode.fish
      creates: /usr/share/code/code

  - name: Install firefox
    ansible.builtin.shell:
      cmd: fish firefox/firefox.fish
      creates: /usr/bin/firefox
  
  - name: PWAs for Firefox native package
    ansible.builtin.shell:
      cmd: |
        # Install required packages for third-party repositories
        sudo apt update
        sudo apt install debian-archive-keyring # Debian-only
        sudo apt install curl gpg apt-transport-https
        # Import GPG key and enable the repository
        curl -fsSL https://packagecloud.io/filips/FirefoxPWA/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/firefoxpwa-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/firefoxpwa-keyring.gpg] https://packagecloud.io/filips/FirefoxPWA/any any main" | sudo tee /etc/apt/sources.list.d/firefoxpwa.list > /dev/null
        # Refresh repositories and install the package
        sudo apt update
        sudo apt install firefoxpwa
        # Create an apparmor profile to get rid of security warnings
        sudo cp firefox/firefoxpwa.apparmor /etc/apparmor.d/firefoxpwa
      creates: /usr/bin/firefoxpwa

  - name: Install zotero
    ansible.builtin.shell:
      cmd: fish zotero/zotero.fish
      creates: /usr/bin/zotero

  - name: Install ollama
    ansible.builtin.shell:
      cmd: curl -fsSL https://ollama.com/install.sh | sh
      creates: /usr/local/bin/ollama

  - name: Install llm cli
    ansible.builtin.shell:
      cmd: pipx install llm && llm install llm-ollama
      creates: ~/.local/bin/llm
    become_user: "{{ target_user }}"

  - name: Install uv for Python
    ansible.builtin.shell:
      cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
      creates: "/home/{{ target_user }}/.local/bin/uv"
    register: uv_install
    become_user: "{{ target_user }}"

  - name: Install uv completions
    vars:
      completion_file: "/home/{{ target_user }}/.config/fish/completions/uv.fish"
    ansible.builtin.shell:
      cmd: "uv generate-shell-completion > {{ completion_file }}"
      creates: "{{ completion_file }}"
    when: uv_install is success
    become_user: "{{ target_user }}"
